### ISSUE TITLE
Note that new requirements can break existing ecosystems

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-ietf-oauth-security-topics#26]
We need to mention that implementing the new requirements (e.g., precise redirect_uri matching) can break existing ecosystems.

**Comment by selfissued** [comment]
The spec should also be clear that if servers reject OpenID Connect requests not using PKCE, they will potentially be incompatible with nearly every OpenID Connect Relying Party.  Note that the OpenID Certification program https://openid.net/certification/#RPs does not require OPs or RPs to implement PKCE (since `nonce` is used).

Given that there's not a security reason for PKCE when `nonce` is used (at least for Confidential Clients), requiring PKCE would be an unnecessary breaking change.  The spec should be clear on this point.

**Comment by danielfett** [comment]
My initial concern had already been addressed in the intro. I clarified in https://github.com/oauthstuff/draft-ietf-oauth-security-topics/pull/49

The PKCE issue has been discussed and better explained in the other changes since the issue was opened.
