### ISSUE TITLE
Refresh tokens: what is the ID?

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-ietf-oauth-security-topics#7]
Comment from Mike Jones:

> 4.12. Refresh Token Protection – The draft says “refresh tokens belonging to the same grant may share a common id”.  Augment this description to say what this ID is and where it is located, and if there’s a pertinent standard or other reference for this ID, please include a citation.

The text in question is this:

    Implementation note: refresh tokens belonging to the same grant
    may share a common id. If any of those refresh tokens is used at
    the authorization server, the authorization server uses this
    common id to look up the currently active refresh token and can
    revoke it.

I'm not sure what the original intention of that text is. Torsten?

**Comment by tlodderstedt** [comment]
It gives a hint how one could implement replay detection. A naive implementation (like our first implementation at DT) would store all refresh tokens ever issued and match them if an invalid token is presented to the AS. The most effective implementation I have ever seen (the second DT implementation :-)) works differently. First of all, the grant is represented as an object independent of refresh tokens. Every refresh token refers to the underlying grant using its grant id. Since every refresh token is just a database handle, the grant id is made a part of that handle. This is necessary since invalidating a refresh token means deleting it from the database. 
Making the grant id part of the refresh token (handle) makes it easy to detect replay and what active refresh token belongs to that particular grant. 

1) check the RT
2) if the RT is invalid, get the grant id and search for the active refresh token with the same grant id and revoke if

Note: depending on the implementation, it is possible to have multiple active refresh tokens per grant id.

**Comment by danielfett** [comment]
Fixed in 783dadf.
